model: # Model specific parameters
  base_params:
    model_args: "pretrained=/hy-tmp/temp/Qwen2.5-3B-GRPO,dtype=bfloat16" # Model args that you would pass in the command line
  generation: # Generation specific parameters
    temperature: 0.1
    repetition_penalty: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    seed: 42
    top_k: -1
    min_p: 0.0
    top_p: 0.9
    max_new_tokens: 4096